-- 002_create_reviews_table.sql

-- Create the reviews table
CREATE TABLE public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  title TEXT NOT NULL,
  summary TEXT,
  category TEXT,
  rating NUMERIC(2, 1) CHECK (rating >= 1 AND rating <= 5), -- e.g., 4.5
  author_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL
);

-- Add comments for clarity
COMMENT ON TABLE public.reviews IS 'Stores all reviews for products and services.';
COMMENT ON COLUMN public.reviews.author_id IS 'The user who wrote the review.';

-- Enable Row Level Security for the reviews table
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Create policies for the reviews table
-- 1. Anyone can read all reviews.
CREATE POLICY "Reviews are public and viewable by everyone."
  ON public.reviews FOR SELECT USING (TRUE);

-- 2. Logged-in users can create new reviews.
CREATE POLICY "Users can create their own reviews."
  ON public.reviews FOR INSERT WITH CHECK (auth.uid() = author_id);

-- 3. Users can update only their own reviews.
CREATE POLICY "Users can update their own reviews."
  ON public.reviews FOR UPDATE USING (auth.uid() = author_id);

-- 4. Users can delete only their own reviews.
CREATE POLICY "Users can delete their own reviews."
  ON public.reviews FOR DELETE USING (auth.uid() = author_id);