-- Create the main table to store business/product/service profiles
CREATE TABLE public.businesses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  description TEXT,
  address TEXT,
  service_area TEXT,
  phone_number TEXT,
  website_url TEXT,
  business_email TEXT,
  operating_hours JSONB,
  services TEXT[],
  pricing_info TEXT,
  year_founded INT,
  is_insured BOOLEAN DEFAULT FALSE,
  license_info TEXT,
  category TEXT,
  owner_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  revuoo_score NUMERIC(3, 1),
  is_verified BOOLEAN NOT NULL DEFAULT FALSE
);

-- Add comments for clarity
COMMENT ON TABLE public.businesses IS 'Stores profiles for all businesses, products, and services that can be reviewed.';
COMMENT ON COLUMN public.businesses.slug IS 'URL-friendly unique identifier for the business profile page.';
COMMENT ON COLUMN public.businesses.owner_id IS 'Links to the Revuoo user who has claimed and manages this profile.';
COMMENT ON COLUMN public.businesses.revuoo_score IS 'The calculated proprietary Revuoo Score.';
COMMENT ON COLUMN public.businesses.is_verified IS 'Flagged by Revuoo admins as a verified, legitimate business.';


-- Enable Row Level Security (RLS) for the new table
ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;

-- Create policies for RLS
-- 1. Allow public, anonymous access to read all business profiles.
CREATE POLICY "Business profiles are viewable by everyone."
  ON public.businesses FOR SELECT USING (TRUE);

-- 2. Allow logged-in users to create a new business profile listing.
CREATE POLICY "Users can create business profiles."
  ON public.businesses FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 3. Allow the owner of a profile to update it.
CREATE POLICY "Owners can update their own business profile."
  ON public.businesses FOR UPDATE USING (auth.uid() = owner_id);