-- Creates a table to store the results from the AI moderation analysis

CREATE TABLE public.review_ai_analysis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id BIGINT NOT NULL UNIQUE REFERENCES public.reviews(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  safety_rating TEXT, -- e.g., 'SAFE', 'FLAGGED'
  summary TEXT, -- A quick summary of the review generated by the AI
  sentiment TEXT, -- e.g., 'POSITIVE', 'NEGATIVE', 'NEUTRAL'
  raw_response JSONB -- Stores the full response from the Gemini API for debugging
);

COMMENT ON TABLE public.review_ai_analysis IS 'Stores results of AI analysis on user reviews for moderation purposes.';