-- This table stores the AI-generated summaries (synthesis) of all reviews for a business.

CREATE TABLE public.business_ai_synthesis (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL UNIQUE REFERENCES public.businesses(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  overall_sentiment TEXT, -- e.g., 'OVERWHELMINGLY_POSITIVE', 'MOSTLY_POSITIVE', 'MIXED', 'MOSTLY_NEGATIVE'
  
  -- We use jsonb to store flexible lists of pros and cons identified by the AI
  common_themes_pros JSONB, -- e.g., [{"theme": "Professionalism", "mentions": 12}, {"theme": "Quality of work", "mentions": 9}]
  common_themes_cons JSONB, -- e.g., [{"theme": "Communication issues", "mentions": 3}]

  -- A one-paragraph summary generated by the AI
  generated_summary TEXT,

  -- The version of the AI model used, for future reference
  model_version TEXT
);

-- Add comments for clarity
COMMENT ON TABLE public.business_ai_synthesis IS 'Stores AI-generated summaries and thematic analysis of reviews for a business.';
COMMENT ON COLUMN public.business_ai_synthesis.business_id IS 'A direct link to the business this summary is for.';
COMMENT ON COLUMN public.business_ai_synthesis.last_updated_at IS 'The timestamp when the summary was last regenerated.';

-- Create a trigger to automatically update the 'last_updated_at' timestamp
CREATE TRIGGER handle_synthesis_update
  BEFORE UPDATE ON public.business_ai_synthesis
  FOR EACH ROW
  EXECUTE PROCEDURE moddatetime(last_updated_at);