-- This table stores metadata for photos uploaded by businesses.

CREATE TABLE public.business_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,

  -- The path to the image file in the 'business-photos' storage bucket.
  photo_path TEXT NOT NULL,

  caption TEXT,
  is_cover_photo BOOLEAN DEFAULT FALSE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add comments for clarity
COMMENT ON TABLE public.business_photos IS 'Stores images for business profiles.';
COMMENT ON COLUMN public.business_photos.photo_path IS 'e.g., public/user-id/image-name.jpg';

-- Enable Row Level Security
ALTER TABLE public.business_photos ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies
-- 1. Anyone can view all photos.
CREATE POLICY "Business photos are public and viewable by everyone."
  ON public.business_photos FOR SELECT
  USING (true);

-- 2. Logged-in business owners can upload photos for their own business.
CREATE POLICY "Business owners can upload photos for their own business."
  ON public.business_photos FOR INSERT
  WITH CHECK ( (SELECT owner_id from public.businesses where id = business_id) = auth.uid() );

-- 3. Business owners can delete photos from their own business gallery.
CREATE POLICY "Business owners can delete their own photos."
  ON public.business_photos FOR DELETE
  USING ( (SELECT owner_id from public.businesses where id = business_id) = auth.uid() );