-- This table will store a simple daily count of views for each business profile.

CREATE TABLE public.business_profile_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id BIGINT NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
  
  view_date DATE NOT NULL DEFAULT CURRENT_DATE,
  view_count INT NOT NULL DEFAULT 1,
  
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Ensure that we only have one row per business per day
  CONSTRAINT unique_business_view_per_day UNIQUE (business_id, view_date)
);

-- Add comments for clarity
COMMENT ON TABLE public.business_profile_views IS 'Tracks daily view counts for public business profiles.';

-- We do not need RLS on this table yet, as we will only interact with it
-- from the server-side using the service_role key.