-- This migration creates the 'opportunities' table for the Sales CRM.

-- Step 1: Create a custom type for the opportunity stage.
CREATE TYPE public.opportunity_stage AS ENUM (
    'discovery',
    'demo_scheduled',
    'proposal_sent',
    'negotiation',
    'closed_won',
    'closed_lost'
);

-- Step 2: Create the 'opportunities' table.
CREATE TABLE public.opportunities (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    lead_id bigint NOT NULL,
    assigned_to_profile_id uuid, -- The sales rep who owns this opportunity
    stage public.opportunity_stage NOT NULL DEFAULT 'discovery',
    
    -- The potential value of the deal
    value numeric, -- e.g., 49.00 for a Pro plan
    associated_plan_name text, -- e.g., 'Pro'

    expected_close_date date,
    closed_at timestamptz,
    
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT opportunities_pkey PRIMARY KEY (id),
    -- Each lead can only have one open opportunity
    CONSTRAINT opportunities_lead_id_key UNIQUE (lead_id),
    CONSTRAINT opportunities_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES public.leads(id) ON DELETE CASCADE,
    CONSTRAINT opportunities_assigned_to_fkey FOREIGN KEY (assigned_to_profile_id) REFERENCES public.profiles(id) ON DELETE SET NULL
);

-- Step 3: Add an index for faster lookups by stage.
CREATE INDEX idx_opportunities_stage ON public.opportunities(stage);