-- This migration creates the tables for the Support Tickets module.

-- Step 1: Create custom types for ticket status and priority.
CREATE TYPE public.ticket_status AS ENUM (
    'open',
    'pending',
    'resolved',
    'closed'
);

CREATE TYPE public.ticket_priority AS ENUM (
    'low',
    'medium',
    'high',
    'urgent'
);

-- Step 2: Create the main 'support_tickets' table.
CREATE TABLE public.support_tickets (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    -- The user who submitted the ticket. Can be null if submitted by an unauthenticated user (e.g., via email).
    profile_id uuid,
    -- The admin/staff member the ticket is assigned to.
    assigned_to_profile_id uuid,
    
    subject text NOT NULL,
    status public.ticket_status NOT NULL DEFAULT 'open',
    priority public.ticket_priority NOT NULL DEFAULT 'medium',
    
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
    CONSTRAINT support_tickets_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE SET NULL,
    CONSTRAINT support_tickets_assigned_to_fkey FOREIGN KEY (assigned_to_profile_id) REFERENCES public.profiles(id) ON DELETE SET NULL
);

-- Step 3: Create the 'ticket_replies' table to store the conversation thread.
CREATE TABLE public.ticket_replies (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ticket_id bigint NOT NULL,
    profile_id uuid NOT NULL, -- The user/admin who wrote the reply.
    content text NOT NULL,
    is_internal_note boolean NOT NULL DEFAULT false, -- For private notes visible only to admins
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT ticket_replies_pkey PRIMARY KEY (id),
    CONSTRAINT ticket_replies_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id) ON DELETE CASCADE,
    CONSTRAINT ticket_replies_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id) ON DELETE CASCADE
);

-- Step 4: Add indexes for faster queries.
CREATE INDEX idx_support_tickets_status ON public.support_tickets(status);
CREATE INDEX idx_ticket_replies_ticket_id ON public.ticket_replies(ticket_id);