-- This migration creates the tables for the Integrations module.

-- Step 1: Create a custom type for the integration category.
CREATE TYPE public.integration_category AS ENUM (
    'e-commerce',
    'crm',
    'marketing',
    'communication',
    'analytics'
);

-- Step 2: Create the main 'integrations' table to store a directory of all possible integrations.
CREATE TABLE public.integrations (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text NOT NULL,
    description text,
    logo_url text, -- URL to the integration's logo
    category public.integration_category NOT NULL,
    is_active boolean NOT NULL DEFAULT false, -- Controls if the integration is available for businesses to use
    
    created_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT integrations_pkey PRIMARY KEY (id),
    CONSTRAINT integrations_name_key UNIQUE (name)
);

-- Step 3: Create the 'business_integrations' join table to track which business has enabled which integration.
CREATE TABLE public.business_integrations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    business_id bigint NOT NULL,
    integration_id uuid NOT NULL,
    is_connected boolean NOT NULL DEFAULT false,
    settings jsonb, -- To store API keys, webhooks, or other settings securely
    
    connected_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT business_integrations_pkey PRIMARY KEY (id),
    CONSTRAINT business_integrations_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE,
    CONSTRAINT business_integrations_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES public.integrations(id) ON DELETE CASCADE,
    -- Ensure a business can only have one instance of each integration
    CONSTRAINT business_integrations_business_id_integration_id_key UNIQUE (business_id, integration_id)
);

-- Step 4: Seed the directory with our first A+++ integration target: Zapier.
INSERT INTO public.integrations (name, description, category, is_active)
VALUES 
('Zapier', 'Connect Revuoo to thousands of other apps like Slack, Google Sheets, and Trello.', 'communication', true)
ON CONFLICT (name) DO NOTHING;