-- This is a safe, idempotent script to set up the Integrations tables.

-- Step 1: Create the custom type only if it doesn't already exist.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'integration_category') THEN
        CREATE TYPE public.integration_category AS ENUM (
            'e-commerce',
            'crm',
            'marketing',
            'communication',
            'analytics'
        );
    END IF;
END$$;

-- Step 2: Create the main 'integrations' table if it doesn't exist.
CREATE TABLE IF NOT EXISTS public.integrations (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text NOT NULL,
    description text,
    logo_url text,
    category public.integration_category NOT NULL,
    is_active boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT integrations_pkey PRIMARY KEY (id),
    CONSTRAINT integrations_name_key UNIQUE (name)
);

-- Step 3: Create the 'business_integrations' join table if it doesn't exist.
CREATE TABLE IF NOT EXISTS public.business_integrations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    business_id bigint NOT NULL,
    integration_id uuid NOT NULL,
    is_connected boolean NOT NULL DEFAULT false,
    settings jsonb,
    connected_at timestamptz,
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT business_integrations_pkey PRIMARY KEY (id),
    CONSTRAINT business_integrations_business_id_fkey FOREIGN KEY (business_id) REFERENCES public.businesses(id) ON DELETE CASCADE,
    CONSTRAINT business_integrations_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES public.integrations(id) ON DELETE CASCADE,
    CONSTRAINT business_integrations_business_id_integration_id_key UNIQUE (business_id, integration_id)
);

-- Step 4: Seed the directory with our first A+++ integration target: Zapier.
INSERT INTO public.integrations (name, description, category, is_active)
VALUES 
('Zapier', 'Connect Revuoo to thousands of other apps like Slack, Google Sheets, and Trello.', 'communication', true)
ON CONFLICT (name) DO NOTHING;